name: Elizabeth Haag
favicon: null
layout_spectrum: 0.6388622538652271
typography_spectrum: 0.8212499103974551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eccdcf'
    - '#a7b6bf'
    - '#ffffff'
    - '#5c5656'
    - '#8b8f93'
  brandStrength: 0.9375
  lightness: 0.9375
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
