name: Elizabeth Haag
favicon: null
layout_spectrum: 0.6388622538652271
typography_spectrum: 0.8212499103974551
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e7d5d6'
    - '#b7b1ac'
    - '#808080'
    - '#ae9c78'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
